name: Build/Publish Develop Docs
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Install Docs Dependencies
        run: pip install mkdocs-material mike
      - name: Setup Docs Deploy
        run: |
          git config --global user.name "Docs Deploy"
          git config --global user.email "docs.deploy@fck-nat.dev"
      - name: Deploy Development Docs
        run: mike deploy --push develop
